### PR TITLE
Small fixes, add support for splatting/building `BODYPROG.BIN`

### PR DESCRIPTION
**Pull request by emoose**
Hi thanks for the work on this, tried setting it up but ran into some issues, luckily were only minor though and was able to mostly get them fixed, and got some initial support added for `BODYPROG.BIN`.

Figured it's worth making a PR in case anyone else wants to give this a try too.

- changed `silentassets` tool to only decrypt the bodyprog.bin/b_konami.bin files, and don't try decrypting map overlays since they don't seem encrypted
- fixed some issues with SLUS_007.07, there was some problem with things getting added to `.rodata` and then discarded, but adding `section_order` to yaml seems to fix that, also added missing jlabel to macros file
- added config for splatting `BODYPROG.BIN` & added it to makefile, assembles very close ~~but there's 8 extra padding bytes at the end, haven't found a way to get rid of them yet, maybe can just add some hack in makefile~~ seems `--no-pad-sections` fixes this
- some minor readme.md fixes

Unfortunately BODYPROG makes use of cop2 which made splat turn some funcs into data defines instead and break build, adding the funcs to symbol_addresses file works luckily - did try checking if `disasm_unknown` in latest splat version might help it but that just disassembled it into some weird opcodes, ah well.  
(E: oh seems those were the actual GTE opcodes, adding `include/gte.inc` lets it assemble fine - fixed that in my main branch: https://github.com/emoose/silent-hill-decomp/)

E: latest commit changed to use PsyQ 4.3, with that I was able to get some small decompiled boot funcs to compile to matching asm

### CODE REVIEW

**Comment by Vatuu** [comment]
Hey, sorry for the delay, kinda forgot the project existed. But I am probably reviving it now. LGTM

**Comment by Vatuu** [comment]
You mind pushing the other changes, mainly the GTE opcode stuff as well?

**Comment by Vatuu** [comment]
Issues have been re-enabled. As for the psyq version, so far 4.4's compiler is giving us good results, we've been using that homebrew psyq build as well. Then again, the build structure of the project needs a pretty major rewrite to accomodate for the new structure I set up. Speaking of which, you may want to familiarize yourself with that before creating a PR.

**Comment by emoose** [comment]
Ah right didn't notice you updated the cc1psx, the makefile still mentions 2.7.2 which is what got me muddled:
https://github.com/Vatuu/silent-hill-decomp/blob/9c108e907a8a25aaa89e6de6481c5d744ec62da8/Makefile#L44

Yeah will reorganize my stuff for the new setup, one thing I was wondering about is whether this could made to work with sotn-decomp's [decompile.py script](https://github.com/Xeeynamo/sotn-decomp/blob/master/tools/decompile.py), was able to hack the script to get it working locally but maybe there's a better way with organizing things how it expects instead.

**Comment by Vatuu** [comment]
That script does look interesting, but I thing writing a new one will be better in the long run. The current makefile is a complete disaster and non-functional, and I am going to throw it out in favour of ninja, but looking at this python script makes me think that a customized solution like that without a fancy pre-existing build script might work just as well. Either that, or just ninja, but I'll still have to see about that. As for decompiling individual functions, I _think_ splat does a decent enough job for now.

**Pull request merged**
